gitops-runtime:
  global:
    codefresh:
      accountId: 6836ecad79f7b44a0ed2b1ac
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
      isConfigurationRuntime: true
